cluster:
  name: control-plane-metrics-test

externalServices:
  prometheus:
    host: https://prometheus.example.com
    tenantId: 1000
    basicAuth:
      username: "12345"
      password: "It's a secret to everyone"

metrics:
  apiserver:
    enabled: true
  etcd:
    enabled: true

logs:
  pod_logs:
    enabled: false

  cluster_events:
    enabled: false
