{{- if and .Values.externalServices.prometheus.secret.create .Values.metrics.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-monitoring.prometheus.secretname" . }}
  namespace: {{ .Values.externalServices.prometheus.secret.namespace | default .Release.Namespace }}
type: Opaque
data:
{{- with .Values.externalServices.prometheus }}
  {{ .hostKey }}: {{ required ".Values.externalServices.prometheus.host is required to use metrics. Please set it and try again." .host | b64enc | quote }}
  {{- if .basicAuth.username }}
  {{ .basicAuth.usernameKey }}: {{ .basicAuth.username | toString | b64enc | quote }}
  {{- end }}
  {{- if .basicAuth.password }}
  {{ .basicAuth.passwordKey }}: {{ .basicAuth.password | toString | b64enc | quote }}
  {{- end }}
  {{- if .tenantId }}
  {{ .tenantIdKey }}: {{ .tenantId | toString | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .Values.externalServices.loki.secret.create (and .Values.logs.enabled (or .Values.logs.pod_logs.enabled .Values.logs.cluster_events.enabled)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-monitoring.loki.secretname" . }}
  namespace: {{ .Values.externalServices.loki.secret.namespace | default .Release.Namespace }}
type: Opaque
data:
{{- with .Values.externalServices.loki }}
  {{ .hostKey }}: {{ required ".Values.externalServices.loki.host is required to use metrics. Please set it and try again." .host | b64enc | quote }}
  {{- if .basicAuth.username }}
  {{ .basicAuth.usernameKey }}: {{ .basicAuth.username | toString | b64enc | quote }}
  {{- end }}
  {{- if .basicAuth.password }}
  {{ .basicAuth.passwordKey }}: {{ .basicAuth.password | toString | b64enc | quote }}
  {{- end }}
  {{- if .tenantId }}
  {{ .tenantIdKey }}: {{ .tenantId | toString | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .Values.externalServices.tempo.secret.create .Values.traces.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-monitoring.tempo.secretname" . }}
  namespace: {{ .Values.externalServices.tempo.secret.namespace | default .Release.Namespace }}
type: Opaque
data:
{{- with .Values.externalServices.tempo }}
  {{ .hostKey }}: {{ required ".Values.externalServices.tempo.host is required to use traces. Please set it and try again." .host | b64enc | quote }}
  {{- if .basicAuth.username }}
  {{ .basicAuth.usernameKey }}: {{ .basicAuth.username | toString | b64enc | quote }}
  {{- end }}
  {{- if .basicAuth.password }}
  {{ .basicAuth.passwordKey }}: {{ .basicAuth.password | toString | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
