---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-agent.serviceAccountName" (index .Subcharts "grafana-agent") }}
    namespace: {{ .Release.Namespace }}
