---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}
rules:
  - apiGroups:
      - ""
      - discovery.k8s.io
      - networking.k8s.io
    resources:
      - configmaps
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.grafana.com
    resources:
      - podlogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
      - probes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}
  labels:
    {{- include "grafana-agent.labels" (index .Subcharts "grafana-agent") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-agent.serviceAccountName" (index .Subcharts "grafana-agent") }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent-logs") }}
rules:
  - apiGroups:
      - ""
      - discovery.k8s.io
      - networking.k8s.io
    resources:
      - configmaps
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.grafana.com
    resources:
      - podlogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
      - probes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent-logs") }}
  labels:
    {{- include "grafana-agent.labels" (index .Subcharts "grafana-agent-logs") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent-logs") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-agent.serviceAccountName" (index .Subcharts "grafana-agent-logs") }}
    namespace: {{ .Release.Namespace }}
